version: '3.8'

services:
  client:
    build:
      context: ./client
      target: dev
    volumes:
      - ./client:/app
      - /app/node_modules
    command: npm start
    environment:
      - NODE_ENV=development
      - REACT_APP_API_URL=http://localhost:5001/api
    ports:
      - 3000:3000
    depends_on:
      - server
    networks:
      - pos-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  server:
    build:
      context: ./server
      target: dev
    volumes:
      - ./server:/app
      - /app/node_modules
    command: npm run dev
    environment:
      - NODE_ENV=development
      - MONGODB_URI=mongodb://mongodb:27017/pos
    ports:
      - 5001:5001
    depends_on:
      - mongodb
    networks:
      - pos-network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5001/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - pos-network
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh localhost:27017/test --quiet
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  seed:
    build:
      context: ./server
    command: ["node", "dist/seed.js"]
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/pos
    restart: "no"
    profiles: ["seed"]
    networks:
      - pos-network

networks:
  pos-network:
    driver: bridge

volumes:
  mongodb_data: 